# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: One-way Pipeline (Nightly)

on:
  workflow_dispatch:
  schedule:
     - cron: '40 12 * * *'

permissions: write-all

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Update and Apply
      run: |
        python main.py
      env:
        PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }} 
        USE_GITHUB_ACTION: ${{ vars.USE_GITHUB_ACTION }}
    - name: Move to repo
      run: |
        cd ${{ vars.REPO_PATH }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Run the Maven
      run: |
        cd ${{ vars.REPO_PATH }}
        mvn package
    - name: Move to staging
      run: |
        mv "./liliths-throne-public-dev/target/Lilith's Throne (linux)" "liliths-throne-linux"
    - name: Zip
      run: |
        zip -r "liliths-throne-linux" "liliths-throne-linux"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with: 
        name: "liliths-throne-linux"
        path: "liliths-throne-linux.zip"
        retention-days: 7
        
  build-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Update and Apply
      shell: bash
      run: |
        python main.py
      env:
        PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }} 
        USE_GITHUB_ACTION: ${{ vars.USE_GITHUB_ACTION }}
    - name: Move to repo
      shell: bash
      run: |
        cd ${{ vars.REPO_PATH }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Modify pom file
      shell: bash
      run: |
        python exe_bundle.py
    - name: Run the Maven
      shell: bash
      run: |
        cd ${{ vars.REPO_PATH }}
        mvn package -Dtarget.platform=win -Dexclude.platform=linux
    - name: Add JRE
      shell: bash
      run: |
          jlink --module-path $JAVA_HOME/jmods/ --add-modules ALL-MODULE-PATH --output "./liliths-throne-public-dev/target/Lilith's Throne (win)/jre"
    - name: Move to staging
      shell: bash
      run: |
        mv "./liliths-throne-public-dev/target/Lilith's Throne (win)" "liliths-throne-win"
    - name: Zip
      shell: bash
      run: |
        zip -r "liliths-throne-win" "liliths-throne-win"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with: 
        name: "liliths-throne-win"
        path: "liliths-throne-win.zip"
        retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-win]
    
    steps:
    - name: Download a Linux Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: "liliths-throne-linux"
    - name: Download a Win Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: "liliths-throne-win"
    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(date "+%y.%m.%d")" >> $GITHUB_ENV
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.RELEASE_VERSION }}"
        prerelease: true
        title: "Release ${{ env.RELEASE_VERSION }}"
        files: |
          *.zip
