# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: One-way Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  update-apply:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Update and Apply
      run: |
        python main.py
      env:
        PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }} 
    - name: Move to folder
      run: |
        ls
        cd ./lilith-throne-public-dev
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run the Maven
      run: |
        mvn package
    - run: mkdir staging && cp -r target/* staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
