# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: One-way Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  update-apply:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Update and Apply
      run: |
        python main.py
      env:
        PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }} 
        USE_GITHUB_ACTION: ${{ vars.USE_GITHUB_ACTION }}

  build-win:
    runs-on: ubuntu-latest
    needs: update-apply

    steps:
    - name: Move to repo
      run: |
        cd ${{ vars.REPO_PATH }}
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Run the Maven
      run: |
        cd ${{ vars.REPO_PATH }}
        mvn package -Dtarget.platform=win -Dexclude.platform=linux
    - name: Move to staging
      run: |
        mv "./liliths-throne-public-dev/target/Lilith's Throne (win)" staging-win
    - name: Zip
      run: |
        zip -r staging-win staging-win

  build-linux:
    runs-on: ubuntu-latest
    needs: update-apply

    steps:
    - name: Move to repo
      run: |
        cd ${{ vars.REPO_PATH }}
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Run the Maven
      run: |
        cd ${{ vars.REPO_PATH }}
        mvn package
    - name: Move to staging
      run: |
        mv "./liliths-throne-public-dev/target/Lilith's Throne (linux)" staging-linux
    - name: Zip
      run: |
        zip -r staging-linux staging-linux
  
  release:
    runs-on: ubuntu-latest
    needs: [build-win, build-linux]

    steps:
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "{{ $secrets.GH_TOKEN }}"
        prerelease: false
        files: ./*.zip
    
